#!/bin/sh

echo "\033[1mStarting Discord Bots\033[0m"

cd /usr/local/src/bots/

for d in */; do
  echo "\033[1mDiscord Bot %d\033[0m"
  (cd "$d" && npm link discord.io && NODE_ENV=production pm2 start index.js --no-daemon)
done
